--8--
--8.1--


CREATE TABLE TEST_TRIGGER(
	ID INT
)

CREATE TRIGGER Table_name_insert
ON TEST_TRIGGER
FOR INSERT
AS
BEGIN
	PRINT 'NEW RECORD INSERTED'
END

INSERT INTO TEST_TRIGGER VALUES(101)
--8.2--

CREATE TRIGGER Table_name_UPDATE
ON TEST_TRIGGER
FOR UPDATE
AS
BEGIN
	PRINT 'NEW RECORD UPDATED'
END

UPDATE TEST_TRIGGER SET ID = 105


--8.3--
CREATE TRIGGER Table_name_DELETE
ON TEST_TRIGGER
FOR DELETE
AS
BEGIN
	PRINT 'RECORD DELETED'
END


--8.4--

CREATE TABLE Table_Name_Log(
	LogID INT IDENTITY(1,1) PRIMARY KEY,
	Event_Table_name_id int,
	Event_Text VARCHAR(100),
	Event_Date DATETIME
)


CREATE TRIGGER Table_Name_Log
ON TEST_TRIGGER
FOR INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @TEST_TRIGGER_ID INT, @Delete_ID INT
	SELECT @TEST_TRIGGER_ID = ID FROM inserted
	SELECT @Delete_ID = ID FROM deleted


select * from Table_Name_Log
